---
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: End-to-End (E2E) Tests
jobs:
  e2e:
    strategy:
      fail-fast: true
      matrix:
        kubernetes:
          - v1.20.7
          - v1.21.2
      max-parallel: 2
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y make gcc

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ matrix.kubernetes }}

      - name: Create KinD cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.11.1
          node_image: kindest/node:${{ matrix.kubernetes }}
          cluster_name: kind
          config: test/kind/config.yaml
          wait: 120s

      - name: Verify KinD cluster
        run: make verify-kind

      - name: Install Registry
        run: make install-registry

      - name: Add cluster hosted registry name to /etc/hosts
        run: echo "127.0.0.1 registry.registry.svc.cluster.local" | sudo tee -a /etc/hosts

      - name: Installing Shipwright Build Controller
        run: make install-shipwright

      - name: Build Application (shp)
        run: make build

      - name: End-to-End Tests
        run: |
          make test-e2e
